name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install

      - name: Deploy to GH Pages
        run: |
          git config --global user.email "${{ secrets.EMAIL }}"
          git config --global user.name "${{ secrets.USER_NAME }}"
          git remote set-url origin https://${{ secrets.PERSONAL_REPO_TOKEN }}@github.com/Mouaz/mouaz.github.io.git
          npm run deploy