name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm install
      - run: npm run predeploy
      - run: npm run deploy

      - name: Deploy to GH Pages
        run: |
          git config --global user.email ${{ secrets.GITHUB_EMAIL }}
          git config --global user.name Mouaz
          git remote set-url origin https://${{ secrets.GITHUB_TOKEN }}@github.com/Mouaz/mouaz.github.io.git
          npm run deploy